erDiagram
    ecommerce{
        interger customer_id pk
        text customer_first_name
        text customer_last_name
        text category_name
        text product_name
        text customer_segment
        text customer_city
        text customer_state
        text customer_country
        text customer_region
        text delivery_status
        date order_date
        integer order_id
        date ship_date
        text shipping_type
        real days_for_shipment
        real days_for_shipment_real
        real order_item_discount
        real sales_per_order
        real order_quantity
        real profit_per_order
    }

    demograpy{
        integer YEAR
        integer SERAL
        INTEGER MONTH
        REAL HWTFINL
        INTERGER CPSID
        INTERGER ASECFLAG
        REAL ASECWTH
        INTEGER NUMPREC
        TEXT REGION
        TEXT STATEFIP
        TEXT METRO
        INTEGER PERNUM
        REAL WTFINL
        TEXT CPSIDP
        TEXT CPSIDV
        REAL ASECWT
        INTERGER AGE
        INTERGER SEX
        TEXT RACE
        TEXT MARST
        TEXT BPL
        TEXT CITIZEN
        TEXT HISPAN
        TEXT EMPSTAT
        TEXT IND
        TEXT EDUC
    }

    youtube{
        text video_id pk
        text title
        date publishedAt
        text channelId
        text channelTitle
        text categoryId
        date trending_date
        text tags
        interger view_count
        interger likes
        interger dislikes
        interger comment_count
        text thumbnail_link
        text comments_disabled
        text ratings_disabled
        text description
    }