erDiagram
    Trend {
        int trend_id pk
        int date_id FK
        int location_id FK
        int ptrend_id FK
        int vtrend_id FK
        real total_sales
        real total_quantity
        real total_profit
        real total_orders
        real avg_discount
        real total_views
        real total_likes
        real total_dislikes
        real total_comments
    }

    Time {
        int date_id PK
        int year
        int month
        int quarter
        int day
        text dayofweek
    }

    Location {
        int location_id PK
        int population
        real avg_household
        real avg_age
        real male_rate
        text race_distribution
        text marital_distribution
        text citizenship_distribution
        int employment_count
        text education_distribution
    }

    ProductTrend {
        int ptrend_id PK
        int product_id pk
        text category
        text product_name
        int cusmtomer_count
        text customer_segment_distribution
        real sales
        real quantity
        real profit 
        real discount
    }

    YouTubeVideoTrend {
        int vtrend_id PK
        text top_categories
        text top_tags
        text video_1st
        text description_1st
        text video_2nd
        text description_2nd
        text video_3rd
        text description_3rd
    }


    Trend }o--|| Time : "by time"
    Trend }o--|| Location : "in region"
    Trend }o--|| ProductTrend : "about product"
    Trend }o--|| YouTubeVideoTrend : "about YouTube video"
